spring:
  application:
    name: name=burn-chuck
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
  swagger-ui:
    tags-sorter: none
    operations-sorter: none
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
cloud:
   aws:
     s3:
       bucket: ${BUCKET_NAME} # 버킷 이름
     stack.auto: false
     region.static: ${BUCKET_REGION} # 버킷 리전
     credentials:
       access-key: ${ACCESS_KEY} # 엑세스 키
       secret-key: ${SECRET_KEY} # 시크릿 키

jwt:
  secret:
    key: ${JWT_SECRET_KEY}
